"""Manual tariff option overrides.

Use this file to curate options per service when auto-extraction misses details,
especially when prices are inside images.

Schema:
SERVICE_TARIFF_OVERRIDES = {
    "service-slug": [
        {"label": "Option", "price_label": "49 EUR", "notes": "Optional note"},
    ]
}
"""

SERVICE_TARIFF_OVERRIDES = {
    "epilation-femme": [
        {"label": "Levres ou menton", "price_label": "12 EUR a 15 EUR", "notes": ""},
        {"label": "Sourcils entretien ligne", "price_label": "18 EUR a 22 EUR", "notes": "Selon technique et sensibilite cutanee."},
        {"label": "Sourcils redefinition ligne", "price_label": "25 EUR a 29 EUR", "notes": "Restructuration complete."},
        {"label": "Maillot bresilien (echancre)", "price_label": "28 EUR a 38 EUR", "notes": "Selon cire employee."},
        {"label": "Maillot americain (echancre+)", "price_label": "32 EUR a 44 EUR", "notes": "Selon cire employee."},
        {"label": "Maillot integral (+ levres)", "price_label": "39 EUR a 49 EUR", "notes": "Selon cire employee."},
        {"label": "Aisselles", "price_label": "14 EUR a 20 EUR", "notes": ""},
        {"label": "1/2 jambes", "price_label": "25 EUR a 42 EUR", "notes": "Selon cire employee."},
        {"label": "Cuisses", "price_label": "28 EUR a 49 EUR", "notes": "Selon cire employee."},
        {"label": "Jambes entieres", "price_label": "49 EUR a 88 EUR", "notes": "Selon cire employee."},
        {"label": "Forfait 1/2 jambes + maillot simple + aisselles", "price_label": "46 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait 1/2 jambes + maillot bresilien + aisselles", "price_label": "50 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait 1/2 jambes + maillot americain + aisselles", "price_label": "65 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait 1/2 jambes + maillot integral + aisselles", "price_label": "73 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait jambes entieres + maillot simple + aisselles", "price_label": "75 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait jambes entieres + maillot bresilien + aisselles", "price_label": "85 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait jambes entieres + maillot americain + aisselles", "price_label": "95 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Forfait jambes entieres + maillot integral + aisselles", "price_label": "98 EUR", "notes": "Abonnement 10 seances disponible."},
        {"label": "Vajacial soin pubien post-epilatoire", "price_label": "129 EUR", "notes": "Hors epilation."},
        {"label": "Offre Aroma-Zone maillot echancre + aisselles", "price_label": "39 EUR", "notes": ""},
    ],
    "epilation-homme": [
        {"label": "Nez ou oreilles", "price_label": "14 EUR", "notes": ""},
        {"label": "Sourcils (ligne restructuration)", "price_label": "30 EUR a 39 EUR", "notes": "Selon technique."},
        {"label": "1/2 jambes", "price_label": "45 EUR a 79 EUR", "notes": "Selon cire employee."},
        {"label": "Jambes entieres", "price_label": "89 EUR a 135 EUR", "notes": "Selon cire employee."},
        {"label": "Bras", "price_label": "35 EUR a 42 EUR", "notes": "Selon cire employee."},
        {"label": "1/2 bras", "price_label": "19 EUR a 35 EUR", "notes": ""},
        {"label": "Maillot integral", "price_label": "75 EUR", "notes": ""},
        {"label": "SIF (sillon inter-fessier)", "price_label": "25 EUR", "notes": ""},
        {"label": "Fesses", "price_label": "42 EUR a 45 EUR", "notes": "Selon technique."},
        {"label": "Aisselles", "price_label": "22 EUR a 25 EUR", "notes": "Selon technique."},
        {"label": "Dos ou torse (a partir de)", "price_label": "49 EUR", "notes": "Selon surface."},
        {"label": "Nuque", "price_label": "12 EUR", "notes": ""},
        {"label": "Vajacial soin pubis post-epilatoire", "price_label": "159 EUR", "notes": "Reparateur et anti-poils sous-cutanes, hors epilation."},
    ],
    "epilation-au-fil": [
        {"label": "Sourcils", "price_label": "35 EUR", "notes": "Abonnement 10 seances: 25 EUR."},
        {"label": "Levres", "price_label": "15 EUR", "notes": ""},
        {"label": "Menton", "price_label": "16 EUR", "notes": "Abonnement 10 seances: 11 EUR."},
        {"label": "Visage entier", "price_label": "79 EUR", "notes": "Abonnement 10 seances: 59 EUR."},
        {"label": "Joues", "price_label": "29 EUR", "notes": ""},
        {"label": "Restructuration a la pince", "price_label": "Sur devis", "notes": "Option mentionnee sur la grille: possibilite de realiser a la pince."},
    ],
    "soins-visage-bio": [
        {"label": "Kobido Mix Mukhabyangha - seance", "price_label": "85 EUR", "notes": "Offre idee cadeau."},
        {"label": "Kobido Mix Mukhabyangha - cure 5 seances", "price_label": "315 EUR", "notes": ""},
        {"label": "Kobido Mix Plus (avec soin Mer Morte) - seance", "price_label": "109 EUR", "notes": ""},
        {"label": "Kobido Mix Plus - cure 5 seances", "price_label": "479 EUR", "notes": ""},
        {"label": "Kobido Max (or 24 carats + perle de caviar + ventouses) - seance", "price_label": "210 EUR", "notes": ""},
        {"label": "Kobido Max - cure 5 seances", "price_label": "699 EUR", "notes": ""},
        {"label": "Kobido Ayurvedique", "price_label": "79 EUR", "notes": "Soin de base."},
        {"label": "Kobido+ (ventouses anti-age + leds trilumieres)", "price_label": "125 EUR", "notes": "Effet liftant immediat."},
        {"label": "Kobido++ (anti-age optimum)", "price_label": "135 EUR", "notes": "Version renforcee."},
        {"label": "Peeling bio purifiant profond", "price_label": "69 EUR", "notes": "Soin de base."},
        {"label": "Peeling Bio+ (purifiant + hydratant)", "price_label": "89 EUR", "notes": "Avec 2 masques."},
        {"label": "Peeling Bio purifiant + hydratant + anti-age trilumiere", "price_label": "109 EUR", "notes": "Soin combine."},
        {"label": "Soin visage ethnique hydratant/purifiant", "price_label": "59 EUR", "notes": "Soin de base."},
        {"label": "Soin visage anti-age", "price_label": "95 EUR a 210 EUR", "notes": "Selon protocole."},
        {"label": "Black Pearl peaux noires/metissees", "price_label": "125 EUR", "notes": "Soin cible hyperpigmentation."},
        {
            "label": "Soin tenseur raffermissant Mer Morte",
            "price_label": "99 EUR",
            "notes": "Purifiant, equilibrant, raffermissant et anti-rides.\n"
            "Nettoyage de peau, gommage eclaircissant et masque magnetique aux mineraux.\n"
            "Lifting mecanique et massage ayurvedique/japonais pour optimiser la penetration des actifs.\n"
            "Resultat: peau raffermie et detente intense.",
        },
        {
            "label": "Soin anti-age prestige Mer Morte (1h30)",
            "price_label": "135 EUR",
            "notes": "Soin premium anti-age: nettoyage intense (peeling bio ou gommage),\n"
            "deux masques anti-age eclaircissant puis liftant,\n"
            "associes a un kobido (japonais) et un mokabyangha (ayurvedique).\n"
            "Resultat: teint lumineux, rides visiblement attenuees, detente profonde.",
        },
        {
            "label": "Soin anti-age liftant mecanique Sweet Palping",
            "price_label": "65 EUR",
            "notes": "Palpe roule liftant non electrique avec ventouses faciales en verre.\n"
            "Remodele l'ovale du visage, repulpe les rides, stimule l'oxygeneration cellulaire\n"
            "et donne un effet bonne mine immediate.",
        },
        {"label": "Sweet Palping visage - cure 5 seances", "price_label": "259 EUR", "notes": ""},
        {"label": "Sweet Palping visage - cure 10 seances", "price_label": "489 EUR", "notes": ""},
        {
            "label": "Jeunesse intense",
            "price_label": "149 EUR",
            "notes": "Combinaison complete: peeling bio, Sweet Palping,\n"
            "Kobido + Mokhabyangha + Face Lift, puis soin anti-rides Mer Morte.",
        },
        {"label": "Jeunesse intense - cure 5 seances", "price_label": "599 EUR", "notes": ""},
        {"label": "Traitement jeunesse tri-lumiere", "price_label": "70 EUR", "notes": "Effet lifting immediat."},
        {"label": "Tri-lumiere - cure 5 seances", "price_label": "250 EUR", "notes": ""},
        {"label": "Tri-lumiere - cure 10 seances", "price_label": "350 EUR", "notes": ""},
        {"label": "Option ventouses anti-age repulpantes", "price_label": "30 EUR", "notes": "Option complementaire."},
        {"label": "Option luminotherapie", "price_label": "29 EUR", "notes": "Option complementaire."},
        {"label": "Option plaque exfoliante + ultrasons", "price_label": "20 EUR", "notes": "Option complementaire."},
        {"label": "Option haute frequence", "price_label": "20 EUR", "notes": "Option complementaire."},
        {"label": "Option gommage eclaircissant Mer Morte", "price_label": "20 EUR", "notes": "Option complementaire."},
        {"label": "Option masque aux actifs Mer Morte", "price_label": "30 EUR", "notes": "Option complementaire."},
        {"label": "Option elixirs precieux + luminotherapie", "price_label": "40 EUR", "notes": "Option complementaire."},
        {"label": "Option vapozone", "price_label": "15 EUR", "notes": "Option complementaire."},
        {"label": "Option gua sha / rouleaux quartz-jade / kansa", "price_label": "10 EUR", "notes": "Option complementaire."},
        {"label": "Offre Aroma-Zone soin visage hydra-purifiant", "price_label": "39 EUR", "notes": "Au lieu de 59 EUR."},
    ],
    "black-pearl-peaux-noires": [
        {"label": "Black Pearl - soin magique", "price_label": "125 EUR", "notes": "Soin cible peaux noires et metissees."},
        {"label": "Maquillage jour", "price_label": "49 EUR", "notes": ""},
        {"label": "Soin corps gommage", "price_label": "39 EUR", "notes": ""},
        {"label": "Soin corps enveloppement", "price_label": "39 EUR", "notes": ""},
    ],
    "soins-corps-bio": [
        {"label": "Soin Vajacial femme", "price_label": "119 EUR", "notes": "Post-epilation maillot."},
        {"label": "Soin Vajacial homme", "price_label": "150 EUR", "notes": "Post-epilation maillot."},
        {"label": "Gommage au choix", "price_label": "39 EUR", "notes": ""},
        {"label": "Enveloppement au choix", "price_label": "49 EUR", "notes": ""},
        {"label": "Gommage + enveloppement", "price_label": "85 EUR", "notes": ""},
    ],
    "minceur-jambes-lourdes": [
        {"label": "1 zone - 1 seance", "price_label": "65 EUR", "notes": ""},
        {"label": "2 zones - 1 seance", "price_label": "99 EUR", "notes": ""},
        {"label": "1 zone - 5 seances", "price_label": "299 EUR", "notes": ""},
        {"label": "2 zones - 5 seances", "price_label": "499 EUR", "notes": ""},
        {"label": "1 zone - 10 seances", "price_label": "579 EUR", "notes": ""},
        {"label": "2 zones - 10 seances", "price_label": "869 EUR", "notes": ""},
        {"label": "Seance drainage", "price_label": "95 EUR", "notes": ""},
        {"label": "Cure 5 seances drainage", "price_label": "450 EUR", "notes": ""},
    ],
    "massage-bio": [
        {"label": "Massage energetique intuitif 30 min", "price_label": "75 EUR", "notes": "Forfait 5 massages: 289 EUR."},
        {"label": "Massage energetique intuitif 60 min", "price_label": "125 EUR", "notes": "Forfait 5 massages: 459 EUR."},
        {"label": "Massage energetique intuitif 90 min", "price_label": "165 EUR", "notes": ""},
        {"label": "Massage energetique intuitif 120 min", "price_label": "220 EUR", "notes": ""},
        {"label": "Massage 4 mains 30 min", "price_label": "139 EUR", "notes": ""},
        {"label": "Massage 4 mains 60 min", "price_label": "249 EUR", "notes": ""},
        {"label": "Massage Shantala bebe + initiation maman 30 min", "price_label": "59 EUR", "notes": ""},
        {"label": "Initiation massage duo (1 jour)", "price_label": "549 EUR", "notes": ""},
        {"label": "Offre Aroma-Zone massage du dos 30 min", "price_label": "39 EUR", "notes": "Au lieu de 59 EUR."},
    ],
    "gestion-du-stress": [
        {"label": "Gestion du stress - 1 seance", "price_label": "75 EUR", "notes": ""},
        {"label": "Gestion du stress - cure 5 seances", "price_label": "290 EUR", "notes": ""},
    ],
    "femme-enceinte-jeune-maman": [
        {"label": "Massage drainant jambes (30 min)", "price_label": "59 EUR", "notes": ""},
        {"label": "Massage cocooning + soin visage ethnique (100 min)", "price_label": "138 EUR", "notes": ""},
        {"label": "Epilation maillot integral", "price_label": "45 EUR", "notes": ""},
        {"label": "Gommage + enveloppement + massage (120 min)", "price_label": "169 EUR", "notes": ""},
        {"label": "Shantala", "price_label": "49 EUR", "notes": ""},
        {"label": "Forfait femme enceinte et jeune maman", "price_label": "399 EUR", "notes": ""},
    ],
    "hammam-sauna": [
        {"label": "Hammam / sauna 30 a 45 min", "price_label": "49 EUR", "notes": ""},
        {"label": "Hammam / sauna duo (tarif par personne)", "price_label": "45 EUR", "notes": ""},
        {"label": "Hammam / sauna groupe (tarif par personne)", "price_label": "40 EUR", "notes": ""},
        {"label": "Acces hammam avec savon noir", "price_label": "59 EUR", "notes": "Preparation ideale avant soin corps."},
    ],
    "rituels-orientaux-spa": [
        {"label": "Rituel oriental decouverte", "price_label": "119 EUR", "notes": "Hammam + gommage + hydratation."},
        {"label": "Rituel oriental signature", "price_label": "189 EUR", "notes": "Version longue et personnalisee."},
        {"label": "Rituel oriental premium", "price_label": "279 EUR", "notes": ""},
        {"label": "Rituel oriental prestige", "price_label": "239 EUR", "notes": ""},
        {"label": "Rituel oriental duo long", "price_label": "499 EUR", "notes": ""},
        {"label": "Rituel rose + massage 60 min", "price_label": "389 EUR", "notes": ""},
    ],
    "onglerie-bio": [
        {"label": "Soin mains anti-age de luxe", "price_label": "159 EUR", "notes": "Nouveaute 2026."},
        {"label": "Vernis traditionnel - depose simple", "price_label": "5 EUR", "notes": ""},
        {"label": "Vernis traditionnel - depose + limage", "price_label": "10 EUR", "notes": ""},
        {"label": "Vernis traditionnel - depose + soin", "price_label": "15 EUR", "notes": ""},
        {"label": "Vernis semi-permanent pose avec manucure", "price_label": "35 EUR", "notes": ""},
        {"label": "Vernis semi-permanent pose avec pedicure", "price_label": "55 EUR", "notes": ""},
        {"label": "Option French", "price_label": "15 EUR", "notes": ""},
    ],
    "manucure-pedicure-bio": [
        {"label": "Manucure spa complete", "price_label": "39 EUR", "notes": "Mise en forme, cuticules, gommage, modelage."},
        {"label": "Pedicure spa complete", "price_label": "59 EUR", "notes": "Soin profond avec callosites."},
        {"label": "Soin paraffine mains", "price_label": "25 EUR", "notes": "En option ou en cure."},
        {"label": "Soin paraffine pieds", "price_label": "29 EUR", "notes": "En option ou en cure."},
        {"label": "Soin anti-taches mains", "price_label": "45 EUR", "notes": "Soin cible anti-age."},
        {"label": "Forfait mains + pieds", "price_label": "89 EUR", "notes": "Version spa complete."},
        {"label": "Reparation ongle casse", "price_label": "8 EUR", "notes": "Tarif unitaire."},
    ],
    "beaute-du-regard": [
        {"label": "Soin Browlift (effet lifte 6 semaines)", "price_label": "Sur devis", "notes": "soin restructurant et fixateur des sourcils."},
        {"label": "Rehaussement de cils Lashlift (6 a 8 semaines)", "price_label": "Sur devis", "notes": "courbure naturelle, teinture recommandee en complement."},
        {"label": "Soin Lashfiller cure 3 seances", "price_label": "Sur devis", "notes": "densifie, nourrit et restructure la fibre du cil."},
        {"label": "Microblading - 1 seance", "price_label": "199 EUR", "notes": ""},
        {"label": "Retouche / suivi", "price_label": "55 EUR", "notes": ""},
        {"label": "Epilation et restructuration a la cire", "price_label": "25 EUR", "notes": ""},
        {"label": "Epilation a la pince", "price_label": "35 EUR", "notes": ""},
        {"label": "Epilation et restructuration au fil", "price_label": "35 EUR", "notes": ""},
        {"label": "Epilation et restructuration au miel", "price_label": "29 EUR", "notes": ""},
        {"label": "Teinture sourcils traditionnelle", "price_label": "31 EUR", "notes": ""},
        {"label": "Teinture sourcils longue duree", "price_label": "39 EUR", "notes": ""},
    ],
    "maquillage-evenementiel": [
        {"label": "Maquillage Flash", "price_label": "29 EUR", "notes": ""},
        {"label": "Maquillage Jour", "price_label": "49 EUR", "notes": ""},
        {"label": "Maquillage Soir", "price_label": "69 EUR", "notes": ""},
        {"label": "Maquillage Oriental", "price_label": "79 EUR", "notes": ""},
        {"label": "Maquillage de scene", "price_label": "99 EUR", "notes": ""},
        {"label": "Cours auto-maquillage jour", "price_label": "89 EUR", "notes": ""},
        {"label": "Cours auto-maquillage jour et soir", "price_label": "110 EUR", "notes": ""},
        {"label": "Programme jeunes 8 a 16 ans", "price_label": "165 EUR", "notes": "Soin + initiation maquillage + manucure + epilation."},
    ],
    "maquillage-permanent": [
        {"label": "Diagnostic maquillage permanent", "price_label": "Tarif sur demande", "notes": "A completer depuis grille image/atelier."},
        {"label": "Programme sur mesure", "price_label": "Sur devis", "notes": "A completer depuis grille image/atelier."},
    ],
}