# Generated by Django 6.0.3 on 2026-03-19 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("short_intro", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("cover_image", models.ImageField(blank=True, upload_to="categories/")),
                ("legacy_url", models.URLField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(default="Les secrets d'ambre", max_length=180),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Institut de beaute bio a Montpellier - soins personnalises",
                        max_length=220,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Rituels beaute et bien-etre", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Soins orientaux, naturels et personnalises. Votre institut vous accompagne avec douceur et expertise."
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, upload_to="hero/")),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("contact_phone_display", models.CharField(blank=True, max_length=32)),
                ("address_line", models.CharField(blank=True, max_length=200)),
                ("postal_code_city", models.CharField(blank=True, max_length=120)),
                ("opening_hours", models.CharField(blank=True, max_length=180)),
                (
                    "booking_label",
                    models.CharField(default="Prendre rendez-vous", max_length=80),
                ),
                ("booking_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("seo_description", models.TextField(blank=True)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                ("footer_note", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "verbose_name": "Parametres du site",
                "verbose_name_plural": "Parametres du site",
            },
        ),
        migrations.CreateModel(
            name="StandalonePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("hero_image", models.ImageField(blank=True, upload_to="pages/")),
                ("show_in_nav", models.BooleanField(default=True)),
                ("nav_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nav_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180)),
                ("short_description", models.TextField(blank=True)),
                ("details_html", models.TextField(blank=True)),
                ("duration_text", models.CharField(blank=True, max_length=80)),
                (
                    "price_label",
                    models.CharField(
                        help_text="Ex: 69EUR, 95-210EUR, Cure 5 seances: 315EUR",
                        max_length=80,
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("booking_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="services/")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="institute.category",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "slug"),
                        name="uniq_service_slug_by_category",
                    )
                ],
            },
        ),
    ]
