# Generated by Django 6.0.3 on 2026-03-19 17:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="duration_text",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_from",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_label",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_to",
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex: Solo, Duo, Cure 5 seances", max_length=140
                    ),
                ),
                ("duration_text", models.CharField(blank=True, max_length=80)),
                (
                    "price_label",
                    models.CharField(help_text="Ex: 49EUR, 95-210EUR", max_length=80),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="institute.service",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
