# Generated by Django 6.0.3 on 2026-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0002_remove_service_duration_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="certification_image",
            field=models.ImageField(blank=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="certification_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="gps_notice",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_offer_text",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
