# Generated by Django 6.0.3 on 2026-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0003_sitesettings_certification_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("website_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="partners/")),
                ("external_image_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
