# Generated by Django 6.0.3 on 2026-03-19 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0004_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeFlexibleSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("body_html", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="home/flexible/")),
                ("external_image_url", models.URLField(blank=True)),
                (
                    "video_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="URL d'embed video (YouTube, Vimeo, etc.).",
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RitualPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("text", models.TextField()),
                (
                    "icon_class",
                    models.CharField(
                        default="bi bi-stars",
                        help_text="Classe Bootstrap Icons (ex: bi bi-stars). Banque d'icones: https://icons.getbootstrap.com/",
                        max_length=80,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("text", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tripadvisor_url",
            field=models.URLField(blank=True),
        ),
    ]
