# Generated by Django 6.0.3 on 2026-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0005_homeflexiblesection_ritualpoint_testimonial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="details_html",
            field=models.TextField(blank=True),
        ),
    ]
