# Generated by Django 6.0.3 on 2026-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0006_tariff_details_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("website_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="certifications/")),
                ("external_image_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="tariff",
            name="promo_price_label",
            field=models.CharField(blank=True, help_text="Ex: 39EUR", max_length=80),
        ),
    ]
