# Generated by Django 6.0.3 on 2026-03-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0007_certification_tariff_promo_price_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_maps_url",
            field=models.URLField(blank=True),
        ),
    ]
