# Generated by Django 6.0.3 on 2026-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0008_certification_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image optionnelle pour le tarif",
                null=True,
                upload_to="tariffs/",
            ),
        ),
    ]
