# Generated by Django 6.0.3 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0009_tariff_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="certification_image",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="certification_label",
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Téléphone de contact"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True, upload_to="hero/", verbose_name="Image hero (En-tête)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.TextField(
                default="Soins orientaux, naturels et personnalises. Votre institut vous accompagne avec douceur et expertise.",
                verbose_name="Sous-titre hero",
            ),
        ),
    ]
