# Generated by Django 6.0.3 on 2026-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0010_remove_sitesettings_certification_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nom du tag"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="cta_label",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Texte du bouton"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="cta_url",
            field=models.URLField(blank=True, verbose_name="Lien du bouton"),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Description (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mots-clés (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="seo_title",
            field=models.CharField(
                blank=True,
                max_length=70,
                verbose_name="Titre pour moteur de recherche (SEO)",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="homeflexiblesection",
            name="cta_label",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Texte du bouton"
            ),
        ),
        migrations.AlterField(
            model_name="homeflexiblesection",
            name="cta_url",
            field=models.URLField(blank=True, verbose_name="Lien du bouton"),
        ),
        migrations.AlterField(
            model_name="homeflexiblesection",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="homeflexiblesection",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="ritualpoint",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="ritualpoint",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="service",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Description (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="seo_title",
            field=models.CharField(
                blank=True,
                max_length=70,
                verbose_name="Titre pour moteur de recherche (SEO)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_note",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="Texte pied de page (footer)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="google_maps_url",
            field=models.URLField(blank=True, verbose_name="Lien Google Maps"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.URLField(blank=True, verbose_name="Lien iframe de la carte"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_title",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="Titre de la carte"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="seo_description",
            field=models.TextField(
                blank=True, verbose_name="Description globale (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="seo_keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mots-clés (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="standalonepage",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="standalonepage",
            name="nav_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre dans le menu"
            ),
        ),
        migrations.AlterField(
            model_name="standalonepage",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Description (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="standalonepage",
            name="seo_keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mots-clés (SEO)"
            ),
        ),
        migrations.AlterField(
            model_name="standalonepage",
            name="seo_title",
            field=models.CharField(
                blank=True,
                max_length=70,
                verbose_name="Titre pour moteur de recherche (SEO)",
            ),
        ),
        migrations.AlterField(
            model_name="standalonepage",
            name="show_in_nav",
            field=models.BooleanField(
                default=True, verbose_name="Afficher dans le menu"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="En ligne (publiée)"),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l'article"),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="blog/",
                        verbose_name="Image de couverture",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Résumé rapide")),
                ("content", models.TextField(verbose_name="Contenu de l'article")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="institute.tag",
                        verbose_name="Tags associés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-created_at"],
            },
        ),
    ]
