# Generated by Django 6.0.3 on 2026-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institute",
            "0011_tag_alter_category_cta_label_alter_category_cta_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=140)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("external_image_url", models.URLField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="En ligne (publiée)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image galerie",
                "verbose_name_plural": "Images galerie",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
