# Generated by Django 6.0.3 on 2026-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0012_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="gallery/"),
        ),
    ]
