# Generated by Django 6.0.3 on 2026-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0013_alter_galleryimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Mise en avant (Accueil)"
            ),
        ),
    ]
